default: &default
  adapter: sqlite3
  database: spec/db/pose.sqlite3
  pool: 5
  timeout: 5000

postgres:
  adapter: postgresql
  encoding: utf8
  database: pose
  username: pose
  password: pose
  min_messages: WARNING

sqlite:
  <<: *default

postgres_ci:
  adapter: postgresql
  encoding: utf8
  database: pose
  username: postgres
  min_messages: WARNING

sqlite_ci:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500