default: &default
  adapter: sqlite3
  database: spec/db/pose.sqlite3
  pool: 5
  timeout: 5000

mysql2:
  adapter: mysql2
  encoding: utf8
  database: pose
  min_messages: WARNING

mysql:
  adapter: mysql
  encoding: utf8
  database: pose
  min_messages: WARNING

postgres:
  adapter: postgresql
  encoding: utf8
  database: pose
  min_messages: WARNING

sqlite:
  <<: *default

mysql2_ci:
  adapter: mysql2
  encoding: utf8
  database: pose
  username: travis
  min_messages: WARNING

mysql_ci:
  adapter: mysql
  encoding: utf8
  database: pose
  username: travis
  min_messages: WARNING

postgres_ci:
  adapter: postgresql
  encoding: utf8
  database: pose
  min_messages: WARNING

sqlite_ci:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500
